### ISSUE TITLE
Simple test throws expection

### ISSUE THREAD

**Issue by liangw-sec** [sebhenri/HyWF#1]
Hi, 

I ran "python attacks.py -tr ../HyWF_dataset/mptcp-hywf_wifiwifi_2_p1_cells/ -t H" and the code threw an exception "RuntimeError: generator raised StopIteration". 

The runtime messages are attached.

```
Using first of train directories as test directory
Checking data format...
../HyWF_dataset/mptcp-hywf_wifiwifi_2_p1_cells/
Saving format in pickle for dir ../HyWF_dataset/mptcp-hywf_wifiwifi_2_p1_cells/
Done in 0.17896413803100586 seconds...
String to hash is ../HyWF_dataset/mptcp-hywf_wifiwifi_2_p1_cells/../HyWF_dataset/mptcp-hywf_wifiwifi_2_p1_cells/100expfixed
Checking data format...
../HyWF_dataset/mptcp-hywf_wifiwifi_2_p1_cells/
Done in 0.0001227855682373047 seconds...
Generated lists with 3000 test files, 6000 train files
Num consecutive packets: in 20, out 20 (exp)
Num change: times 0, packets 0 (fixed)
Result file is out/out-100-100/flearner_d45b04be80_Hcu-100-100_0.results
1592089251.705705: p_trains are in: 1.0, out: 1.0p_tests are in:1, out:1, data is in train:../HyWF_dataset/mptcp-hywf_wifiwifi_2_p1_cells/, test:../HyWF_dataset/mptcp-hywf_wifiwifi_2_p1_cells/
Extracting...
---- file 12-75.cell (175 features) ----Traceback (most recent call last):
  File "/Users/wangliang/Desktop/HyWF/HyWF_code/code_kfp.py", line 200, in neighborhood
    item = iterator.__next__()  # throws StopIteration if empty.
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "attacks.py", line 921, in <module>
    attacks(args)
  File "attacks.py", line 466, in attacks
    all_train_features, all_test_features, name_features = get_features(args, file_flearner_name, "H")
  File "attacks.py", line 93, in get_features
    all_test_features, all_train_features, name_features = fextractor_pool(args, args.cellf_loc, type)
  File "/Users/wangliang/Desktop/HyWF/HyWF_code/fextractor.py", line 308, in fextractor_pool
    features_loc, name_features, size_before, size_after = write_features\
  File "/Users/wangliang/Desktop/HyWF/HyWF_code/fextractor.py", line 134, in write_features
    features, name_features = extract_Hayes(times, sizes, args.factors_p_est, args.num_consecutive_packets_out) # n_cons_out = n_cons_in)
  File "/Users/wangliang/Desktop/HyWF/HyWF_code/code_kfp.py", line 504, in extract_Hayes
    avg_per_sec, std_per_sec, med_per_sec, min_per_sec, max_per_sec, per_sec = number_per_sec(list_data)
  File "/Users/wangliang/Desktop/HyWF/HyWF_code/code_kfp.py", line 422, in number_per_sec
    for prev,item,next in neighborhood(temp):
RuntimeError: generator raised StopIteration
```

**Comment by sebhenri** [comment]
Hi,
Which version of Python is it? I tried from scratch and this command worked (I'm using Python 3.6).

**Comment by liangw-sec** [comment]
Hi, 

I used Python 3.8. 3.6 is working!  Thanks!

Liang
